twilio:
    account_sid: ${sid}
    auth_token: ${token}
  trial_number: +15005550006

server:
  port: 8080

amazon:
    access:
        key: ${aws_key}
        secret-key: ${aws_secret}
    region: ${region}
    sns: ${sns}
