twilio:
    account_sid: ${sid}
    auth_token: ${token}
    trial_number: ${sender_phone}

server:
    port: 8080

amazon:
    access:
        key: ${aws_key}
        secret-key: ${aws_secret}
    region: ${region}
    sqs: sms
